### ISSUE TITLE
RPM %check section?

### ISSUE THREAD

**Issue by frankcrawford** [rfrail3/tuptime#62]
I've been going through the Fedora package review process and should shortly have tuptime available as part of the various Fedora and EPEL distributions (see https://bugzilla.redhat.com/show_bug.cgi?id=2007918 for more details).

However the question has been raised that there is currently no %check section (it is optional anyway) and what can be done about it?  Is there any suitable testing that could be done?

**Comment by rfrail3** [comment]
Hi Frank,

Great to know that.

About the tests, on Debian, there are the two, one with a simple "tuptime" and the other with "tuptime -v" because .deb have a special requirement for stderr and the verbose output could have the value information in case of a failed test. Both return '0' as sucess, maybe if "tuptime -v" fits well, it'll be enough.

Take a look to https://github.com/rfrail3/tuptime/tree/master/debian/tests

Thanks,

**Comment by rfrail3** [comment]
I just did a quick test with:

```
%check
tuptime -v

```
 and it fails:
```
...
+ cd tuptime-5.0.2
+ tuptime -v
/var/tmp/rpm-tmp.VWaVZR: line 32: tuptime: command not found
error: Bad exit status from /var/tmp/rpm-tmp.VWaVZR (%check)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.VWaVZR (%check)
```
The %check that seems to work is the following one:
```
%check
python3 src/tuptime -v -f /tmp/tuptime.db
```
But it really check more things than the [definition](https://rpm-packaging-guide.github.io/) "Command or series of commands to test the software" because take into relevance the system too. The Tuptime test fits better into Debian [definition](https://ci.debian.net/doc/file.TUTORIAL.html) "i.e. the testing of packages in context as close as possible to a Debian system where the packages subject to testing are properly installed"

As the "%include" is optional, and the current tests doesn't match the right scope, I leave the .specs file without it.

**Comment by rfrail3** [comment]
Hi Frank,

I'm close to release a new version. Do you want to push any update? Maybe the revised spec file?

Thanks,

**Comment by frankcrawford** [comment]
Okay, I'll push the updated spec file in the next day or so.

**Comment by frankcrawford** [comment]
Now pushed updated spec file.

**Comment by rfrail3** [comment]
Great, I also updated the specs file on dev branch.
